//! Island walkability grid.
//!
//! Builds a per-island tile grid marking which tiles are walkable.
//! Used by the A* pathfinder for carrier routing.
//!
//! Walkability rules (from original game analysis):
//! - Terrain tiles (grass, sand, etc.) are walkable
//! - Roads are walkable
//! - Buildings block movement (their full tile footprint)
//! - Water/coast tiles are not walkable
//! - Warehouse tiles are walkable (carriers need to reach them)

use anno_formats::cod::BuildingDef as CodBuilding;
use anno_formats::szs::{source_runtime_island_classification, Island, IslandSourceResourceState};
use std::collections::HashSet;

use crate::source_cell::{source_plantation_path_kind_always_walkable, SourceMapCellState};
use crate::source_route::{
    source_static_map_direction, SourcePathBlockedCellDecision, SourcePathGrid,
    SourcePathTargetRect, SourceTargetDescriptor,
};

/// Static source-map data needed to rebuild the short type-3 civilian route
/// window around a kind-13 location anchor.
#[derive(Debug, Clone, Copy)]
struct SourceCivilianPathCell {
    kind_code: u8,
    production_kind_code: u8,
    kind3_center_cell: bool,
    owner: u8,
    source_ware_slot: u8,
    plantation_path_class: u8,
    path_class: u8,
}

/// Compiled outer kind retained for every INSELHAUS footprint cell. Unlike
/// the civilian route overlay, this exists even when the definition has no
/// type-3 path class, because `FUN_00467940` only inspects map kinds.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct SourceMapKindCell {
    kind_code: u8,
    kind3_center_cell: bool,
    map_owner: u8,
    ware_slot: u8,
    map_direction: u8,
}

/// One six-word candidate record produced by `FUN_00415af0` for the source
/// controller's state-two city search. Bounds are local-cell half-open
/// intervals; `area` is the source record's accumulated horizontal length.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SourceControllerCityRectangle {
    pub x0: u16,
    pub y0: u16,
    pub x1: u16,
    pub y1: u16,
    pub area: u32,
}

/// One six-word segment record emitted by `FUN_004160c0`. State three samples
/// exactly one cell from each segment before scoring its surviving candidates.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SourceControllerCityCandidateSegment {
    pub x0: i32,
    pub y0: i32,
    pub x1: i32,
    pub y1: i32,
    pub length: u32,
}

/// Walkability grid for a single island.
#[derive(Debug, Clone)]
pub struct IslandMap {
    pub island_id: u8,
    /// Source-world coordinate of local grid cell `(0, 0)`. INSEL5 stores
    /// this origin in half-world units; type-4 figure positions use the
    /// doubled coordinate system consumed by `FUN_00444af0`.
    pub source_world_origin: (i32, i32),
    pub width: u16,
    pub height: u16,
    /// Flat grid: true = walkable. Index = y * width + x.
    walkable: Vec<bool>,
    /// Per-tile road flag. Carriers crossing a road tile pay a
    /// reduced path cost so the A* pathfinder prefers roads when
    /// they're available — RE: haeuser.cod `Wegspeed: 145, 120,
    /// 170, 100` (plain ground vs road quad).
    road: Vec<bool>,
    /// Static source path overlay for KARREN `Speedtyp: 2`. Runtime cart
    /// searches clone this and mark same-owner producer roots as callback
    /// cells before running the source weighted wave.
    city_cart_path_template: SourcePathGrid,
    /// Static source path overlay for TRAEGER's inherited `Speedtyp: 0`.
    /// Runtime type-8 dispatch clones this before applying its owner-specific
    /// supplier markers.
    carrier_path_template: SourcePathGrid,
    /// Live-map kind, owner, and type-3 path class replayed from the
    /// scenario's oriented INSELHAUS commands. `FUN_0044b140` samples an
    /// 11 x 11 window from this state for its kind-12 civilian route.
    civilian_path_cells: Vec<Option<SourceCivilianPathCell>>,
    source_map_kind_cells: Vec<Option<SourceMapKindCell>>,
    /// Raw type-2 `Wegspeed` values used by KARREN movement.
    city_cart_movement_speeds: Vec<u16>,
    /// Raw type-0 `Wegspeed` values used by TRAEGER movement.
    carrier_movement_speeds: Vec<u16>,
    /// Raw type-1 `Wegspeed` values used by cavalry type-4 movement.
    cavalry_movement_speeds: Vec<u16>,
    /// Raw type-3 `Wegspeed` values used by kind-12 civilian movement.
    civilian_movement_speeds: Vec<u16>,
    /// Per-cell `Posoffs × 0.028` source terrain elevation. INSELHAUS
    /// commands overwrite this grid in the same oriented-footprint order as
    /// the live map-object table used by source figure constructors.
    source_terrain_heights: Vec<f32>,
    /// Doubled source-grid dimensions returned by `FUN_00463880` for a
    /// static map cell. `FUN_00444fe0` combines these with the descriptor's
    /// local cell coordinate when building a type-4 target rectangle.
    source_land_target_sizes: Vec<Option<(u16, u16)>>,
    /// Static `0x0c`/`0x0d` overlay generated by `FUN_0046f460` for the
    /// type-4 terminal target check. The direct checker only rejects `0x0d`.
    source_kind4_line_of_fire_template: SourcePathGrid,
    /// Eight raw INSEL5 fertility bytes carried over from the
    /// scenario file. Use `active_fertilities()` to iterate the
    /// non-sentinel typed values.
    pub fertilities: [u8; 8],
    /// Source island-runtime u16 at offset `+0x18`, initialized from the
    /// `INSEL5` loader's classification rewrite.
    source_runtime_classification: u16,
    /// Source raw-resource availability and attenuation copied from the
    /// matching `INSEL5` runtime record.
    source_resource_state: IslandSourceResourceState,
}

/// Building kinds that represent walkable terrain or roads.
const WALKABLE_KINDS: &[&str] = &[
    "BODEN",      // Ground/terrain
    "STRASSE",    // Road
    "STRANDMUND", // Beach mouth
    "STRAND",     // Beach
    "MEER",       // Sea (for coastal)
    "FLUSS",      // River
    "MAUER",      // Wall sections can be walked on
    "MAUERSTRAND",
    "PLATZ", // Plaza/square
    "TOR",   // Gate
];

impl IslandMap {
    /// Build a walkability map from island tile data and building definitions.
    pub fn from_island(island: &Island, cod_buildings: &[CodBuilding]) -> Self {
        let width = island.width as u16;
        let height = island.height as u16;
        let size = width as usize * height as usize;

        // Start with all tiles as non-walkable (water/empty)
        let mut walkable = vec![false; size];
        let mut road = vec![false; size];
        let mut city_cart_movement_speeds = vec![100; size];
        let mut carrier_movement_speeds = vec![100; size];
        let mut cavalry_movement_speeds = vec![100; size];
        let mut civilian_movement_speeds = vec![100; size];
        let mut civilian_path_cells = vec![None; size];
        let mut source_map_kind_cells = vec![None; size];
        let mut source_terrain_heights = vec![0.0; size];
        let mut source_land_target_sizes = vec![None; size];
        let source_world_origin = (i32::from(island.x_pos) * 2, i32::from(island.y_pos) * 2);
        let mut source_kind4_line_of_fire_template = SourcePathGrid::new(
            source_world_origin,
            usize::from(width) * 2,
            usize::from(height) * 2,
        );

        // Warehouse positions — always walkable
        let mut warehouse_tiles: HashSet<(u8, u8)> = HashSet::new();

        // Replay INSELHAUS commands in source order. The loader expands each
        // source definition over its oriented footprint before later commands
        // can overwrite those live-map cells.
        for tile in &island.tiles {
            // The INSELHAUS loader adds 0x4e20 to this u16 and resolves the
            // resulting haeuser.cod source ID, rather than a Gfx sprite.
            if let Some(def) = cod_buildings
                .iter()
                .find(|def| def.source_id == tile.source_id())
            {
                let kind = def.kind.as_str();
                let (footprint_width, footprint_height) = if matches!(tile.orientation & 3, 1 | 3) {
                    (def.size.1, def.size.0)
                } else {
                    def.size
                };
                if footprint_width <= 0 || footprint_height <= 0 {
                    continue;
                }
                let source_land_target_size = u16::try_from(footprint_width)
                    .ok()
                    .and_then(|width| width.checked_mul(2))
                    .zip(
                        u16::try_from(footprint_height)
                            .ok()
                            .and_then(|height| height.checked_mul(2)),
                    );
                let is_walkable = is_walkable_kind(kind) || kind == "KONTOR";
                let is_road = kind == "STRASSE";
                let movement_speeds = def.source_path_speeds();
                let line_of_fire_direction = source_static_map_direction(def, *tile).unwrap_or(0);
                for dy in 0..footprint_height {
                    for dx in 0..footprint_width {
                        let x = i32::from(tile.x) + dx;
                        let y = i32::from(tile.y) + dy;
                        if x < 0 || y < 0 || x >= i32::from(width) || y >= i32::from(height) {
                            continue;
                        }
                        let idx = y as usize * width as usize + x as usize;
                        let source_cell_index = match tile.orientation & 3 {
                            0 => dy * def.size.0 + dx,
                            1 => (def.size.1 - 1 - dx) * def.size.0 + dy,
                            2 => (def.size.1 - 1 - dy) * def.size.0 + (def.size.0 - 1 - dx),
                            _ => dx * def.size.0 + (def.size.0 - 1 - dy),
                        };
                        source_map_kind_cells[idx] = Some(SourceMapKindCell {
                            kind_code: def.source_kind_code().unwrap_or(u8::MAX),
                            kind3_center_cell: def.source_kind_code() == Some(3)
                                && source_cell_index == def.size.0.saturating_mul(def.size.1) / 2,
                            map_owner: tile.source_owner(),
                            ware_slot: def.source_ware_slot().unwrap_or(0),
                            map_direction: tile.orientation & 3,
                        });
                        walkable[idx] = is_walkable;
                        road[idx] = is_road;
                        if let Some(speeds) = movement_speeds {
                            carrier_movement_speeds[idx] = u16::from(speeds[0].max(1));
                            cavalry_movement_speeds[idx] = u16::from(speeds[1].max(1));
                            city_cart_movement_speeds[idx] = u16::from(speeds[2].max(1));
                            civilian_movement_speeds[idx] = u16::from(speeds[3].max(1));
                        }
                        if let Some(path_classes) = def.source_path_classes() {
                            civilian_path_cells[idx] = Some(SourceCivilianPathCell {
                                kind_code: def.source_kind_code().unwrap_or(u8::MAX),
                                production_kind_code: def
                                    .source_production_kind_code()
                                    .unwrap_or(u8::MAX),
                                kind3_center_cell: def.source_kind_code() == Some(3)
                                    && source_cell_index
                                        == def.size.0.saturating_mul(def.size.1) / 2,
                                owner: tile.source_owner(),
                                source_ware_slot: def.source_ware_slot().unwrap_or_default(),
                                plantation_path_class: path_classes[0],
                                path_class: path_classes[3],
                            });
                        } else {
                            civilian_path_cells[idx] = None;
                        }
                        source_terrain_heights[idx] = def.source_position_offset as f32 * 0.028;
                        source_land_target_sizes[idx] = source_land_target_size;
                        let raw_origin =
                            (source_world_origin.0 + x * 2, source_world_origin.1 + y * 2);
                        for raw_y in raw_origin.1..=raw_origin.1 + 1 {
                            for raw_x in raw_origin.0..=raw_origin.0 + 1 {
                                source_kind4_line_of_fire_template
                                    .set_direction_marker((raw_x, raw_y), line_of_fire_direction);
                            }
                        }
                        if kind == "KONTOR" {
                            warehouse_tiles.insert((x as u8, y as u8));
                        }
                    }
                }
            }
        }

        let mut city_cart_path_template =
            SourcePathGrid::new((0, 0), usize::from(width), usize::from(height));
        city_cart_path_template
            .populate_static_island_cells(island, cod_buildings, 2, |_, _| false)
            .expect("KARREN Speedtyp is within the four Wegspeed classes");
        let mut carrier_path_template =
            SourcePathGrid::new((0, 0), usize::from(width), usize::from(height));
        carrier_path_template
            .populate_static_island_cells(island, cod_buildings, 0, |_, _| false)
            .expect("TRAEGER Speedtyp is within the four Wegspeed classes");

        Self {
            island_id: island.number,
            source_world_origin,
            width,
            height,
            walkable,
            road,
            city_cart_path_template,
            carrier_path_template,
            civilian_path_cells,
            source_map_kind_cells,
            city_cart_movement_speeds,
            carrier_movement_speeds,
            cavalry_movement_speeds,
            civilian_movement_speeds,
            source_terrain_heights,
            source_land_target_sizes,
            source_kind4_line_of_fire_template,
            fertilities: island.fertilities,
            source_runtime_classification: source_runtime_island_classification(island.width, 0),
            source_resource_state: IslandSourceResourceState::default(),
        }
    }

    /// Attach the `INSEL5` loader's initialized runtime classification.
    pub fn with_source_runtime_classification(mut self, classification: u16) -> Self {
        self.source_runtime_classification = classification;
        self
    }

    /// Return the source island-runtime u16 at offset `+0x18`.
    pub const fn source_runtime_classification(&self) -> u16 {
        self.source_runtime_classification
    }

    /// Attach the matching `INSEL5` resource inputs after the static map has
    /// been replayed from its island command stream.
    pub fn with_source_resource_state(mut self, state: IslandSourceResourceState) -> Self {
        self.source_resource_state = state;
        self
    }

    pub const fn source_resource_state(&self) -> IslandSourceResourceState {
        self.source_resource_state
    }

    pub fn source_resource_strength(&self, ware: u8) -> u8 {
        self.source_resource_state.resource_strength(ware)
    }

    pub const fn source_resource_attenuation(&self) -> u8 {
        self.source_resource_state.attenuation
    }

    pub const fn source_resource_transition_deadline_ticks(&self) -> u32 {
        self.source_resource_state.transition_deadline_ticks
    }

    /// `FUN_0040e8b0`'s raw suitability score for one map-owner selector.
    /// The controller initializer compares these unnormalised scores when no
    /// owned city has at least ten inhabitants in BGRUPPE tiers 2 through 4.
    pub fn source_controller_city_suitability_score(&self, owner: u8) -> i32 {
        let mut score = i32::from(self.width) * i32::from(self.height);
        for cell in &self.source_map_kind_cells {
            let penalty = match cell {
                Some(cell) if cell.map_owner == 7 || cell.map_owner == owner => {
                    match cell.kind_code {
                        10..=12 => 4,
                        25 | 26 => 2,
                        _ => 1,
                    }
                }
                _ => 1,
            };
            score -= penalty;
        }
        score
    }

    /// Replay `FUN_00415af0` over this island's live source kind and owner
    /// grid. The executable scans its half-open `(0, 0)` through
    /// `(width - 1, height - 1)` bounds, first marking vertical runs and then
    /// merging horizontal runs from consecutive rows into six-word records.
    pub fn source_controller_city_rectangles(
        &self,
        owner: u8,
        minimum_width: u16,
        minimum_height: u16,
    ) -> Vec<SourceControllerCityRectangle> {
        let x_limit = usize::from(self.width.saturating_sub(1));
        let y_limit = usize::from(self.height.saturating_sub(1));
        let minimum_width = usize::from(minimum_width);
        let minimum_height = usize::from(minimum_height);
        if x_limit == 0 || y_limit == 0 || minimum_width == 0 || minimum_height == 0 {
            return Vec::new();
        }

        let mut marked = vec![false; usize::from(self.width) * usize::from(self.height)];
        let eligible = |x: usize, y: usize| {
            self.source_map_kind_cells[y * usize::from(self.width) + x].is_some_and(|cell| {
                cell.map_owner == owner && matches!(cell.kind_code, 10..=12 | 31 | 32)
            })
        };

        for x in 0..x_limit {
            let mut run_start = 0;
            let mut run_length = 0;
            for y in 0..y_limit {
                if eligible(x, y) {
                    if run_length == 0 {
                        run_start = y;
                    }
                    run_length += 1;
                    continue;
                }
                if run_length >= minimum_height {
                    for marked_y in run_start..run_start + run_length {
                        marked[marked_y * usize::from(self.width) + x] = true;
                    }
                }
                run_length = 0;
            }
        }

        let mut rectangles = Vec::new();
        let mut previous_lines: Vec<(usize, usize, usize)> = Vec::new();
        for y in 0..y_limit {
            let mut current_lines = Vec::new();
            let mut run_start = 0;
            let mut run_length = 0;
            for x in 0..x_limit {
                if marked[y * usize::from(self.width) + x] {
                    if run_length == 0 {
                        run_start = x;
                    }
                    run_length += 1;
                    continue;
                }
                if run_length != 0 {
                    for marked_x in run_start..run_start + run_length {
                        marked[y * usize::from(self.width) + marked_x] = false;
                    }
                    if run_length >= minimum_width {
                        let run_end = run_start + run_length;
                        let rectangle = previous_lines
                            .iter()
                            .find(|(previous_start, previous_end, _)| {
                                run_start <= *previous_end && *previous_start <= run_end
                            })
                            .map(|(_, _, rectangle)| *rectangle)
                            .unwrap_or_else(|| {
                                if rectangles.len() == 256 {
                                    return usize::MAX;
                                }
                                rectangles.push(SourceControllerCityRectangle {
                                    x0: run_start as u16,
                                    y0: y as u16,
                                    x1: run_end as u16,
                                    y1: y as u16 + 1,
                                    area: 0,
                                });
                                rectangles.len() - 1
                            });
                        if rectangle != usize::MAX {
                            let entry = &mut rectangles[rectangle];
                            entry.x0 = entry.x0.min(run_start as u16);
                            entry.x1 = entry.x1.max(run_end as u16);
                            entry.y1 = y as u16 + 1;
                            entry.area = entry.area.saturating_add(run_length as u32);
                            current_lines.push((run_start, run_end, rectangle));
                        }
                    }
                }
                run_length = 0;
            }
            previous_lines = current_lines;
        }
        rectangles
    }

    /// Replay `FUN_004160c0` for one expanded action-three rectangle. The
    /// first source pass emits vertical segments, then the second emits
    /// horizontal segments, each capped at 256 records in total.
    pub fn source_controller_city_candidate_segments(
        &self,
        owner: u8,
        x0: i32,
        y0: i32,
        x1: i32,
        y1: i32,
        minimum_horizontal_length: u32,
        minimum_vertical_length: u32,
    ) -> Vec<SourceControllerCityCandidateSegment> {
        let mut segments = Vec::new();
        for x in x0..x1 {
            let mut run_start = 0;
            let mut run_length = 0_u32;
            for y in y0..y1 {
                let Some(cell) = self.source_map_kind_cell((x, y)) else {
                    continue;
                };
                if cell.map_owner != owner {
                    continue;
                }
                if source_controller_city_candidate_kind(cell.kind_code)
                    && self.source_controller_city_horizontal_clear(x, y)
                {
                    if run_length == 0 {
                        run_start = y;
                    }
                    run_length = run_length.saturating_add(1);
                    continue;
                }
                if run_length >= minimum_vertical_length && segments.len() < 256 {
                    segments.push(SourceControllerCityCandidateSegment {
                        x0: x,
                        y0: run_start,
                        x1: x,
                        y1: run_start + run_length as i32,
                        length: run_length,
                    });
                }
                run_length = 0;
            }
        }
        for y in y0..y1 {
            let mut run_start = 0;
            let mut run_length = 0_u32;
            for x in x0..x1 {
                let Some(cell) = self.source_map_kind_cell((x, y)) else {
                    continue;
                };
                if cell.map_owner != owner {
                    continue;
                }
                if source_controller_city_candidate_kind(cell.kind_code)
                    && self.source_controller_city_vertical_clear(x, y)
                {
                    if run_length == 0 {
                        run_start = x;
                    }
                    run_length = run_length.saturating_add(1);
                    continue;
                }
                if run_length >= minimum_horizontal_length && segments.len() < 256 {
                    segments.push(SourceControllerCityCandidateSegment {
                        x0: run_start,
                        y0: y,
                        x1: run_start + run_length as i32,
                        y1: y,
                        length: run_length,
                    });
                }
                run_length = 0;
            }
        }
        segments
    }

    fn source_controller_city_horizontal_clear(&self, x: i32, y: i32) -> bool {
        let left = x.min(6);
        for offset in -left..-3 {
            if !self.source_controller_city_clearance_kind((x + offset, y)) {
                return false;
            }
        }
        let right = (i32::from(self.width) - x).min(6);
        for offset in 3..right {
            if !self.source_controller_city_clearance_kind((x + offset, y)) {
                return false;
            }
        }
        true
    }

    fn source_controller_city_vertical_clear(&self, x: i32, y: i32) -> bool {
        let above = y.min(6);
        for offset in -above..-3 {
            if !self.source_controller_city_clearance_kind((x, y + offset)) {
                return false;
            }
        }
        let below = (i32::from(self.height) - y).min(6);
        for offset in 3..below {
            if !self.source_controller_city_clearance_kind((x, y + offset)) {
                return false;
            }
        }
        true
    }

    fn source_controller_city_clearance_kind(&self, position: (i32, i32)) -> bool {
        self.source_map_kind_cell(position)
            .map(|cell| matches!(cell.kind_code, 10..=12 | 19))
            .unwrap_or(true)
    }

    /// `FUN_00417220` with the state-three `param_4 = 1` look-ahead. The
    /// source follows the selected cell's two-bit map direction, skips eight
    /// cells, then accepts only if no remaining cell in that ray has kind 19.
    pub fn source_controller_city_boundary_clear(&self, x: i32, y: i32) -> bool {
        let Some(cell) = self.source_map_kind_cell((x, y)) else {
            return false;
        };
        let (step_x, step_y, available) = match cell.map_direction {
            0 => (0, 1, i32::from(self.height) - y - 1),
            1 => (-1, 0, x),
            2 => (0, -1, y),
            _ => (1, 0, i32::from(self.width) - x - 1),
        };
        let mut position = (x + step_x * 8, y + step_y * 8);
        let mut remaining = available - 2;
        while remaining > 0 {
            remaining -= 1;
            let Some(cell) = self.source_map_kind_cell(position) else {
                // The executable's map allocation includes sea padding beyond
                // this local island grid.
                return true;
            };
            if cell.kind_code != 19 {
                return false;
            }
            position.0 += step_x;
            position.1 += step_y;
        }
        true
    }

    /// `FUN_0040fe80` from one local map cell and a two-bit direction. The
    /// return is the source's one-based line distance, including its special
    /// single-kind-16 run handling.
    pub fn source_controller_city_line_distance(
        &self,
        owner: u8,
        x: i32,
        y: i32,
        direction: u8,
    ) -> u32 {
        let (step_x, step_y, mut remaining) = match direction & 3 {
            0 => (1, 0, i32::from(self.width) - x - 1),
            1 => (0, 1, i32::from(self.height) - y - 1),
            2 => (-1, 0, x),
            _ => (0, -1, y),
        };
        let mut position = (x, y);
        let mut prior_was_kind_16 = false;
        let mut distance = 1_u32;
        while remaining > 0 {
            remaining -= 1;
            position.0 += step_x;
            position.1 += step_y;
            let Some(cell) = self.source_map_kind_cell(position) else {
                return distance;
            };
            if cell.map_owner != owner && cell.map_owner != 7 {
                return distance;
            }
            if cell.kind_code == 16 && !prior_was_kind_16 {
                prior_was_kind_16 = true;
            } else if matches!(cell.kind_code, 1 | 4 | 10..=12 | 18) {
                prior_was_kind_16 = false;
            } else {
                return if distance < 2 { 0 } else { distance };
            }
            distance = distance.saturating_add(1);
        }
        distance
    }

    /// Source map-word direction bits `13..14` used by `FUN_004172e0` to
    /// choose its line-distance ray and final construction offset.
    pub fn source_controller_city_map_direction(&self, x: i32, y: i32) -> Option<u8> {
        self.source_map_kind_cell((x, y))
            .map(|cell| cell.map_direction)
    }

    /// `FUN_00417120` over a clamped local square.
    pub fn source_controller_city_green_density(
        &self,
        owner: u8,
        x: i32,
        y: i32,
        radius: i32,
    ) -> u32 {
        self.source_controller_city_density(owner, x, y, radius, |cell| {
            (cell.ware_slot == 0 && cell.kind_code == 12) || matches!(cell.ware_slot, 0x34 | 0x35)
        })
    }

    /// `FUN_00417030` over a clamped local square.
    pub fn source_controller_city_ware_five_density(
        &self,
        owner: u8,
        x: i32,
        y: i32,
        radius: i32,
    ) -> u32 {
        self.source_controller_city_density(owner, x, y, radius, |cell| cell.ware_slot == 5)
    }

    fn source_controller_city_density(
        &self,
        owner: u8,
        x: i32,
        y: i32,
        radius: i32,
        predicate: impl Fn(SourceMapKindCell) -> bool,
    ) -> u32 {
        let x0 = (x - radius).max(0);
        let y0 = (y - radius).max(0);
        let x1 = (x + radius).min(i32::from(self.width));
        let y1 = (y + radius).min(i32::from(self.height));
        (y0..y1)
            .flat_map(|row| (x0..x1).map(move |column| (column, row)))
            .filter_map(|position| self.source_map_kind_cell(position))
            .filter(|cell| cell.map_owner == owner && predicate(*cell))
            .count() as u32
    }

    /// The attenuation write in the latter branch of `FUN_0046b3e0`.
    /// Values below twelve are cleared after the truncating half-step.
    pub fn decay_source_resource_attenuation(&mut self) -> u8 {
        let halved = self.source_resource_state.attenuation / 2;
        self.source_resource_state.attenuation = if halved < 12 { 0 } else { halved };
        self.source_resource_state.attenuation
    }

    /// Active (non-sentinel) fertilities decoded into the typed
    /// `Fertility` enum. Mirrors `Island::active_fertilities`
    /// but on the simulation-side map so callers don't need to
    /// keep the original `Island` around.
    pub fn active_fertilities(&self) -> Vec<anno_formats::szs::Fertility> {
        self.fertilities
            .iter()
            .filter_map(|&b| anno_formats::szs::Fertility::from_byte(b))
            .collect()
    }

    /// Whether a local island-grid cell lies within this INSEL5 map.
    #[inline]
    pub fn contains_local(&self, x: i32, y: i32) -> bool {
        x >= 0 && y >= 0 && x < i32::from(self.width) && y < i32::from(self.height)
    }

    /// Convert a type-4 source-world position to the corresponding local
    /// INSEL5 grid cell. `FUN_00444af0` doubles local coordinates when it
    /// resolves static island descriptors, so figure coordinates are divided
    /// by two relative to the island origin before grid routing.
    #[inline]
    pub fn source_world_to_local(&self, world: (i32, i32)) -> Option<(i32, i32)> {
        let local = (
            (world.0 - self.source_world_origin.0).div_euclid(2),
            (world.1 - self.source_world_origin.1).div_euclid(2),
        );
        self.contains_local(local.0, local.1).then_some(local)
    }

    /// `FUN_0046a4d0`'s island lookup admits a five-unit source-world border
    /// around the doubled INSEL5 extent before returning the matching island.
    #[inline]
    pub fn source_contains_world_with_margin(&self, world: (i32, i32)) -> bool {
        let max_x = self.source_world_origin.0 + i32::from(self.width) * 2;
        let max_y = self.source_world_origin.1 + i32::from(self.height) * 2;
        world.0 >= self.source_world_origin.0 - 5
            && world.0 < max_x + 5
            && world.1 >= self.source_world_origin.1 - 5
            && world.1 < max_y + 5
    }

    /// Convert a local INSEL5 grid cell to its doubled source-world waypoint.
    /// Type-4 movement advances toward this waypoint in raw world units, so
    /// callers must retain an existing odd coordinate until it naturally
    /// crosses the local-cell boundary.
    #[inline]
    pub fn local_to_source_world(&self, local: (i32, i32)) -> Option<(i32, i32)> {
        self.contains_local(local.0, local.1).then_some((
            self.source_world_origin.0 + local.0 * 2,
            self.source_world_origin.1 + local.1 * 2,
        ))
    }

    /// Resolve a type-4 idle anchor into its raw source-world position.
    /// Static kinds `0x33`/`0x34` address one local cell on the descriptor's
    /// island. `FUN_00444af0` doubles a kind-`0x37` world cell and retains a
    /// kind-`0x38` raw figure coordinate.
    pub fn source_land_idle_anchor(
        &self,
        descriptor: SourceTargetDescriptor,
    ) -> Option<(i32, i32)> {
        match descriptor.kind() {
            0x33 | 0x34 if descriptor.bytes()[1] == self.island_id => self.local_to_source_world((
                i32::from(descriptor.bytes()[2]),
                i32::from(descriptor.bytes()[3]),
            )),
            SourceTargetDescriptor::WORLD_COORDINATE_KIND
            | SourceTargetDescriptor::FIXED_POINT_COORDINATE_KIND => descriptor
                .source_land_route_coordinate()
                .filter(|&world| self.source_world_to_local(world).is_some()),
            _ => None,
        }
    }

    /// Resolve a type-4 descriptor into the raw target rectangle returned by
    /// `FUN_00444fe0`. Static `0x32`/`0x33`/`0x34` descriptors use the
    /// selected cell's retained oriented footprint; packed coordinates retain
    /// the source fallback `1 × 1` rectangle.
    pub fn source_land_target_rect(
        &self,
        descriptor: SourceTargetDescriptor,
    ) -> Option<SourcePathTargetRect> {
        match descriptor.kind() {
            0x32 | 0x33 | 0x34 if descriptor.bytes()[1] == self.island_id => {
                let local = (
                    i32::from(descriptor.bytes()[2]),
                    i32::from(descriptor.bytes()[3]),
                );
                let index = self.local_index(local)?;
                let (width, height) = *self.source_land_target_sizes.get(index)?.as_ref()?;
                SourcePathTargetRect::new(
                    self.local_to_source_world(local)?,
                    usize::from(width),
                    usize::from(height),
                )
            }
            SourceTargetDescriptor::WORLD_COORDINATE_KIND
            | SourceTargetDescriptor::FIXED_POINT_COORDINATE_KIND => descriptor
                .source_land_route_coordinate()
                .and_then(|origin| SourcePathTargetRect::new(origin, 1, 1)),
            _ => None,
        }
    }

    /// Check if a tile is walkable.
    #[inline]
    pub fn is_walkable(&self, x: i32, y: i32) -> bool {
        if !self.contains_local(x, y) {
            return false;
        }
        self.walkable[y as usize * self.width as usize + x as usize]
    }

    /// True if `(x, y)` is a road tile. Used by the pathfinder to
    /// favour road-following routes (RE: haeuser.cod `Wegspeed`
    /// quads — plain-ground 145/120 off-road vs 170/100 on-road).
    #[inline]
    pub fn is_road(&self, x: i32, y: i32) -> bool {
        if x < 0 || y < 0 || x >= self.width as i32 || y >= self.height as i32 {
            return false;
        }
        self.road[y as usize * self.width as usize + x as usize]
    }

    /// Clone the static type-2 source-grid overlay for a type-11 city-cart
    /// search. The caller supplies its live owner-specific root markers.
    pub fn city_cart_path_grid(&self) -> SourcePathGrid {
        self.city_cart_path_template.clone()
    }

    /// Clone the static type-0 source-grid overlay for a type-8 TRAEGER
    /// search. The caller supplies the live owner-specific supplier markers.
    pub fn carrier_path_grid(&self) -> SourcePathGrid {
        self.carrier_path_template.clone()
    }

    /// Rebuild the local type-12 plantation-worker grid made by
    /// `FUN_0046f920` and `FUN_004710b0`. The source admits its fixed terrain
    /// kinds, plus cells owned by the root whose compiled ware is the worker's
    /// `Rohstoff`; the root footprint itself carries metadata `0x28`.
    pub fn plantation_worker_path_grid(
        &self,
        center: (i32, i32),
        root: (i32, i32),
        footprint: (u8, u8),
        radius: u8,
        source_owner: u8,
        raw_resource_ware_slot: u8,
        static_cells: &[SourceMapCellState],
    ) -> SourcePathGrid {
        let radius_usize = usize::from(radius);
        let radius = i32::from(radius);
        let width = usize::from(footprint.0.max(1)).saturating_add(radius.max(0) as usize * 2);
        let height = usize::from(footprint.1.max(1)).saturating_add(radius.max(0) as usize * 2);
        let origin = (center.0 - radius, center.1 - radius);
        let mut grid = SourcePathGrid::new(origin, width, height);

        for y in origin.1..origin.1 + height as i32 {
            for x in origin.0..origin.0 + width as i32 {
                grid.mark_direction_blocker((x, y));
                if let Some(static_cell) = static_cells.iter().rev().find(|state| {
                    state.island == self.island_id
                        && i32::from(state.x) == x
                        && i32::from(state.y) == y
                }) {
                    if static_cell
                        .admits_plantation_worker_path(source_owner, raw_resource_ware_slot)
                    {
                        grid.set_traversable_cell((x, y), static_cell.source_path_class);
                    }
                    continue;
                }
                let Some(cell) = self.civilian_path_cell((x, y)) else {
                    continue;
                };
                let fixed_terrain = source_plantation_path_kind_always_walkable(cell.kind_code);
                let matching_raw_resource =
                    cell.owner == source_owner && cell.source_ware_slot == raw_resource_ware_slot;
                if fixed_terrain || matching_raw_resource {
                    grid.set_traversable_cell((x, y), cell.plantation_path_class);
                }
            }
        }

        if let Some(target) = SourcePathTargetRect::new(
            root,
            usize::from(footprint.0.max(1)),
            usize::from(footprint.1.max(1)),
        ) {
            grid.set_target_region_metadata(target, 0x28);
        }
        let _ = grid.block_outside_source_radius_mask(
            radius_usize,
            usize::from(footprint.0.max(1)),
            usize::from(footprint.1.max(1)),
        );
        grid
    }

    /// Rebuild the clipped `35 x 35` terrain-event grid made by
    /// `FUN_004702b0` for a generic type-17 figure. The native overlay uses
    /// fixed terrain kinds, the centre cell of kind 3, and its special
    /// `Ware = 0x35` branch. Every admitted cell gets the fixed `0x20` path
    /// class; matching, unreserved resource cells instead become the `0xa0`
    /// terminal callback cells scanned by `FUN_00471c50`.
    pub fn source_type17_terrain_path_grid(
        &self,
        center: (i32, i32),
        resource_ware_slot: u8,
        static_cells: &[SourceMapCellState],
    ) -> SourcePathGrid {
        const RADIUS: i32 = 17;
        const GRID_SIDE: usize = 35;
        const SPECIAL_TERRAIN_WARE_SLOT: u8 = 0x35;
        const PATH_CLASS: u8 = 0x20;
        const TARGET_METADATA: u8 = 0xa0;

        let origin = (center.0 - RADIUS, center.1 - RADIUS);
        let mut grid = SourcePathGrid::new(origin, GRID_SIDE, GRID_SIDE);

        for y in origin.1..=origin.1 + RADIUS * 2 {
            for x in origin.0..=origin.0 + RADIUS * 2 {
                let position = (x, y);
                grid.mark_direction_blocker(position);

                let civilian_cell = self.civilian_path_cell(position);
                let kind3_center_cell = civilian_cell.is_some_and(|cell| cell.kind3_center_cell);
                if let Some(static_cell) = static_cells.iter().rev().find(|state| {
                    state.island == self.island_id
                        && i32::from(state.x) == x
                        && i32::from(state.y) == y
                }) {
                    let normalized_ware_slot = static_cell.plantation_path_resource_ware_slot();
                    let traversable =
                        source_plantation_path_kind_always_walkable(static_cell.kind_code)
                            || (static_cell.kind_code == 3 && kind3_center_cell)
                            || (static_cell.source_production_kind_code != 10
                                && normalized_ware_slot == SPECIAL_TERRAIN_WARE_SLOT);
                    if traversable {
                        grid.set_traversable_cell(position, PATH_CLASS);
                        if normalized_ware_slot == resource_ware_slot
                            && !static_cell.source_resource_reserved
                        {
                            grid.set_metadata(position, TARGET_METADATA);
                        }
                    }
                    continue;
                }

                let Some(cell) = civilian_cell else {
                    continue;
                };
                let traversable = source_plantation_path_kind_always_walkable(cell.kind_code)
                    || cell.kind3_center_cell
                    || (cell.production_kind_code != 10
                        && cell.source_ware_slot == SPECIAL_TERRAIN_WARE_SLOT);
                if traversable {
                    grid.set_traversable_cell(position, PATH_CLASS);
                    if cell.source_ware_slot == resource_ware_slot {
                        grid.set_metadata(position, TARGET_METADATA);
                    }
                }
            }
        }

        grid
    }

    /// Rebuild the `11 x 11` type-3 path window passed to
    /// `FUN_0046c7d0` by `FUN_0044b140`. The source first blocks every cell,
    /// then permits fixed terrain kinds 1, 13, 18, and 30 plus the selected
    /// permission-mask kinds owned by the spawning root's player.
    pub fn civilian_path_grid(
        &self,
        center: (i32, i32),
        source_owner: u8,
        permission_branch: u8,
    ) -> SourcePathGrid {
        const RADIUS: i32 = 5;
        let origin = (center.0 - RADIUS, center.1 - RADIUS);
        let mut grid = SourcePathGrid::new(origin, 11, 11);
        for y in origin.1..=origin.1 + RADIUS * 2 {
            for x in origin.0..=origin.0 + RADIUS * 2 {
                grid.mark_direction_blocker((x, y));
                let Some(cell) = self.civilian_path_cell((x, y)) else {
                    continue;
                };
                let permission_matched = cell.owner == source_owner
                    && crate::civilian::source_civilian_path_kind_permitted(
                        permission_branch,
                        cell.kind_code,
                    );
                let fixed = matches!(cell.kind_code, 1 | 13 | 18 | 30);
                if fixed || permission_matched {
                    grid.set_traversable_cell(
                        (x, y),
                        cell.path_class | (u8::from(permission_matched) << 7),
                    );
                }
            }
        }
        grid
    }

    /// `FUN_0044b140` resolves the oriented static footprint at a kind-13
    /// root and allocates its kind-12 figure at the integer center
    /// `(width - 1) / 2, (height - 1) / 2` from that root.
    pub fn source_kind12_anchor_center(&self, root: (i32, i32)) -> Option<(i32, i32)> {
        let index = self.local_index(root)?;
        let (raw_width, raw_height) = *self.source_land_target_sizes.get(index)?.as_ref()?;
        let width = i32::from(raw_width / 2).max(1);
        let height = i32::from(raw_height / 2).max(1);
        Some((root.0 + (width - 1) / 2, root.1 + (height - 1) / 2))
    }

    /// Rebuild the source type-3 path window used by `FUN_0047bbc0` and
    /// `FUN_0047c080` while they redistribute a kind-13 residence amount.
    ///
    /// `FUN_004722f0` centers this window on the selected map definition's
    /// oriented footprint and extends each axis by `0x28`; `FUN_004724d0`
    /// then admits its fixed terrain kinds plus compiled production kind 13
    /// when the target map-owner selector matches the center cell. The
    /// `0x2000` mask supplied by both callers contains only that dynamic
    /// kind-13 permission.
    pub fn source_kind13_transfer_path_grid(&self, center: (i32, i32)) -> Option<SourcePathGrid> {
        const RADIUS: i32 = 0x28;
        let center_cell = self.civilian_path_cell(center)?;
        let center_index = self.local_index(center)?;
        let (raw_width, raw_height) = *self.source_land_target_sizes.get(center_index)?.as_ref()?;
        let footprint_width = i32::from(raw_width / 2).max(1);
        let footprint_height = i32::from(raw_height / 2).max(1);
        let origin = (
            center.0 + (footprint_width - 1) / 2 - RADIUS,
            center.1 + (footprint_height - 1) / 2 - RADIUS,
        );
        let width = usize::try_from(footprint_width + RADIUS * 2).ok()?;
        let height = usize::try_from(footprint_height + RADIUS * 2).ok()?;
        let mut grid = SourcePathGrid::new(origin, width, height);

        for y in 0..height {
            for x in 0..width {
                let position = (origin.0 + x as i32, origin.1 + y as i32);
                grid.mark_direction_blocker(position);
                let Some(cell) = self.civilian_path_cell(position) else {
                    continue;
                };
                let owner_matched_kind13 = cell.production_kind_code == 13
                    && (center_cell.owner == 7 || cell.owner == center_cell.owner);
                let fixed_kind = matches!(cell.kind_code, 1 | 11 | 12 | 13 | 18 | 29 | 30);
                if fixed_kind || owner_matched_kind13 {
                    grid.set_traversable_cell(
                        position,
                        cell.path_class | (u8::from(owner_matched_kind13) << 7),
                    );
                }
            }
        }
        Some(grid)
    }

    /// Collect the source map coordinates written through `LAB_00472ad0` by
    /// `FUN_00471fb0` for a kind-13 amount transfer.
    ///
    /// The callback records only high-bit path cells, so this yields
    /// owner-matched kind-13 locations in weighted-wave order. Its fixed
    /// output buffer holds at most forty coordinates.
    pub fn source_kind13_transfer_neighbor_cells(
        &self,
        center: (i32, i32),
    ) -> Option<Vec<(i32, i32)>> {
        const OUTPUT_CAPACITY: usize = 0x28;
        let mut grid = self.source_kind13_transfer_path_grid(center)?;
        let mut neighbors = Vec::new();
        let result = grid.search_with_blocked_cell_callback(center, |position, _| {
            neighbors.push(position);
            if neighbors.len() == OUTPUT_CAPACITY {
                SourcePathBlockedCellDecision::Complete
            } else {
                SourcePathBlockedCellDecision::Expand
            }
        });
        match result {
            Ok(_) | Err(crate::source_route::SourcePathSearchError::NoRoute) => Some(neighbors),
            Err(crate::source_route::SourcePathSearchError::OutOfBounds) => None,
        }
    }

    /// Replay `FUN_00467940` for a kind-13 replacement. The source chooses
    /// the first qualifying edge in top, bottom, left, right order; a map
    /// cell qualifies when its compiled outer kind is `1` or `18`, or when it
    /// is the central compiled cell of outer kind `3`.
    pub fn source_kind13_replacement_orientation(
        &self,
        source_size: (u8, u8),
        fallback_orientation: u8,
        origin: (i32, i32),
    ) -> u8 {
        let (raw_width, raw_height) = source_size;
        let (width, height) = if fallback_orientation & 1 == 0 {
            (i32::from(raw_width), i32::from(raw_height))
        } else {
            (i32::from(raw_height), i32::from(raw_width))
        };
        let (x, y) = origin;
        let edge_cell_allowed = |position| {
            self.source_map_kind_cell(position)
                .is_some_and(|cell| matches!(cell.kind_code, 1 | 18) || cell.kind3_center_cell)
        };
        let x_end = (x + width).min(i32::from(self.width));
        let y_end = (y + height).min(i32::from(self.height));

        if y > 0 && (x..x_end).any(|edge_x| edge_cell_allowed((edge_x, y - 1))) {
            return 2;
        }
        if y + height < i32::from(self.height)
            && (x..x_end).any(|edge_x| edge_cell_allowed((edge_x, y + height)))
        {
            return 0;
        }
        if x > 0 && (y..y_end).any(|edge_y| edge_cell_allowed((x - 1, edge_y))) {
            return 3;
        }
        if x + width < i32::from(self.width)
            && (y..y_end).any(|edge_y| edge_cell_allowed((x + width, edge_y)))
        {
            return 1;
        }
        fallback_orientation & 3
    }

    /// Raw type-0 terrain speed for `FUN_0044a690` TRAEGER movement.
    pub fn carrier_movement_speed(&self, position: (i32, i32)) -> Option<u16> {
        self.movement_speed(&self.carrier_movement_speeds, position)
    }

    /// Raw type-2 terrain speed for `FUN_0044a690` KARREN movement.
    pub fn city_cart_movement_speed(&self, position: (i32, i32)) -> Option<u16> {
        self.movement_speed(&self.city_cart_movement_speeds, position)
    }

    /// Raw source terrain speed for a type-4 `Speedtyp` class.
    pub fn source_land_movement_speed(&self, speed_type: u8, position: (i32, i32)) -> Option<u16> {
        match speed_type {
            0 => self.carrier_movement_speed(position),
            1 => self.movement_speed(&self.cavalry_movement_speeds, position),
            2 => self.city_cart_movement_speed(position),
            3 => self.civilian_movement_speed(position),
            _ => None,
        }
    }

    /// Rebuild the doubled-coordinate type-4 terrain grid used by
    /// `FUN_004581f0` and `FUN_0046f460`. Each INSEL5 cell becomes four raw
    /// route cells. The native builder permits only its fixed terrain kinds;
    /// all building kinds remain direction-blocked for a land-figure route.
    pub fn source_land_path_grid(&self, speed_type: u8) -> Option<SourcePathGrid> {
        if speed_type >= 4 {
            return None;
        }
        let width = usize::from(self.width).checked_mul(2)?;
        let height = usize::from(self.height).checked_mul(2)?;
        let mut grid = SourcePathGrid::new(self.source_world_origin, width, height);

        for y in 0..i32::from(self.height) {
            for x in 0..i32::from(self.width) {
                let local = (x, y);
                let raw_origin = self.local_to_source_world(local)?;
                for raw_y in raw_origin.1..=raw_origin.1 + 1 {
                    for raw_x in raw_origin.0..=raw_origin.0 + 1 {
                        grid.mark_direction_blocker((raw_x, raw_y));
                    }
                }

                let fixed_terrain = matches!(
                    self.civilian_path_kind(local),
                    Some(1 | 11 | 12 | 13 | 18 | 29 | 30)
                );
                if !fixed_terrain {
                    continue;
                }
                let speed = self.source_land_movement_speed(speed_type, local)?;
                let metadata = crate::carrier::source_path_class(speed);
                for raw_y in raw_origin.1..=raw_origin.1 + 1 {
                    for raw_x in raw_origin.0..=raw_origin.0 + 1 {
                        grid.set_traversable_cell((raw_x, raw_y), metadata);
                    }
                }
            }
        }
        Some(grid)
    }

    /// Apply the terminal direct-ray predicate from `FUN_00453e50` to the
    /// currently reconstructed type-4 candidate set. `FUN_0045fac0` writes
    /// `SOLDAT3 + 0x16` into live figure byte zero, so the local candidates
    /// all have source tag 4; the source adds directional unit footprints
    /// only for tags 1 through 3. The remaining relevant overlay is the
    /// static map's `0x0d` cells retained above.
    pub fn source_kind4_line_of_fire_clear(&self, start: (i32, i32), end: (i32, i32)) -> bool {
        self.source_kind4_line_of_fire_template
            .direction_13_ray_clear(start, end, u32::MAX)
    }

    /// `FUN_0046ea40` acceptance for a type-4 partial-route endpoint. The
    /// executable resolves the raw coordinate back to its INSEL5 cell and
    /// accepts only the fixed terrain kinds used by `FUN_0046f460`.
    pub fn source_land_partial_marker_allowed(&self, position: (i32, i32)) -> bool {
        self.source_world_to_local(position).is_some_and(|local| {
            matches!(
                self.civilian_path_kind(local),
                Some(1 | 11 | 12 | 13 | 18 | 29 | 30)
            )
        })
    }

    /// Raw type-3 terrain speed for kind-12 civilian movement.
    pub fn civilian_movement_speed(&self, position: (i32, i32)) -> Option<u16> {
        self.movement_speed(&self.civilian_movement_speeds, position)
    }

    /// Live source map-object kind at a type-3 civilian route endpoint.
    pub fn civilian_path_kind(&self, position: (i32, i32)) -> Option<u8> {
        self.civilian_path_cell(position).map(|cell| cell.kind_code)
    }

    /// Target-cell predicate used by the type-4 native idle branch. Its
    /// source check accepts runtime kind codes `1` and `11`; kind `1` covers
    /// the executable's road and production-label aliases.
    pub fn source_native_idle_target_allowed(&self, position: (i32, i32)) -> bool {
        matches!(self.civilian_path_kind(position), Some(1 | 11))
    }

    /// Source map-cell terrain elevation used to initialise a figure's Z
    /// coordinate. This is `Posoffs × 0.028` after INSELHAUS replay.
    pub fn source_terrain_height(&self, position: (i32, i32)) -> Option<f32> {
        let (x, y) = position;
        if x < 0 || y < 0 || x >= i32::from(self.width) || y >= i32::from(self.height) {
            return None;
        }
        self.source_terrain_heights
            .get(y as usize * self.width as usize + x as usize)
            .copied()
    }

    fn movement_speed(&self, speeds: &[u16], position: (i32, i32)) -> Option<u16> {
        let (x, y) = position;
        if x < 0 || y < 0 || x >= i32::from(self.width) || y >= i32::from(self.height) {
            return None;
        }
        speeds
            .get(y as usize * self.width as usize + x as usize)
            .copied()
            .filter(|speed| *speed != 0)
    }

    fn civilian_path_cell(&self, position: (i32, i32)) -> Option<SourceCivilianPathCell> {
        self.civilian_path_cells
            .get(self.local_index(position)?)
            .copied()
            .flatten()
    }

    fn source_map_kind_cell(&self, position: (i32, i32)) -> Option<SourceMapKindCell> {
        self.source_map_kind_cells
            .get(self.local_index(position)?)
            .copied()
            .flatten()
    }

    fn local_index(&self, position: (i32, i32)) -> Option<usize> {
        self.contains_local(position.0, position.1)
            .then_some(position.1 as usize * self.width as usize + position.0 as usize)
    }

    /// Mark a tile as walkable (e.g., for warehouse placement after map creation).
    pub fn set_walkable(&mut self, x: u16, y: u16, val: bool) {
        if x < self.width && y < self.height {
            self.walkable[y as usize * self.width as usize + x as usize] = val;
        }
    }

    /// A tile is "coastal" if it's walkable AND at least one of its
    /// 4-neighbours is out of bounds — i.e. it sits on the perimeter of
    /// the island's walkable region. Fisheries can only go on coastal tiles.
    pub fn is_coastal(&self, x: i32, y: i32) -> bool {
        if !self.is_walkable(x, y) {
            return false;
        }
        for (dx, dy) in [(1i32, 0i32), (-1, 0), (0, 1), (0, -1)] {
            let nx = x + dx;
            let ny = y + dy;
            if nx < 0 || ny < 0 || nx >= self.width as i32 || ny >= self.height as i32 {
                return true;
            }
        }
        false
    }

    /// True iff the entire `w × h` footprint anchored at `(x, y)` is walkable.
    pub fn can_fit(&self, x: i32, y: i32, w: u16, h: u16) -> bool {
        if x < 0 || y < 0 {
            return false;
        }
        if (x as u32) + w as u32 > self.width as u32 {
            return false;
        }
        if (y as u32) + h as u32 > self.height as u32 {
            return false;
        }
        for dy in 0..h as i32 {
            for dx in 0..w as i32 {
                if !self.is_walkable(x + dx, y + dy) {
                    return false;
                }
            }
        }
        true
    }

    /// Spiral search around `(cx, cy)` (warehouse, typically) for the first
    /// position where `w × h` fits. Returns top-left tile or None.
    pub fn find_open_spot(
        &self,
        cx: u16,
        cy: u16,
        w: u16,
        h: u16,
        max_radius: u16,
    ) -> Option<(u16, u16)> {
        for r in 0..=max_radius as i32 {
            for dy in -r..=r {
                for dx in -r..=r {
                    // Only the ring at the current radius (skip interior).
                    if dx.abs() != r && dy.abs() != r {
                        continue;
                    }
                    let x = cx as i32 + dx;
                    let y = cy as i32 + dy;
                    if self.can_fit(x, y, w, h) {
                        return Some((x as u16, y as u16));
                    }
                }
            }
        }
        None
    }

    /// Like `find_open_spot`, but additionally rejects candidates that
    /// aren't reachable from `anchor` via the walkability graph (BFS).
    /// `anchor` is normally the warehouse tile that will service the new
    /// building. Use this when placement requires a carrier route home.
    pub fn find_reachable_spot(
        &self,
        cx: u16,
        cy: u16,
        w: u16,
        h: u16,
        max_radius: u16,
        anchor: (u16, u16),
    ) -> Option<(u16, u16)> {
        for r in 0..=max_radius as i32 {
            for dy in -r..=r {
                for dx in -r..=r {
                    if dx.abs() != r && dy.abs() != r {
                        continue;
                    }
                    let x = cx as i32 + dx;
                    let y = cy as i32 + dy;
                    if !self.can_fit(x, y, w, h) {
                        continue;
                    }
                    if self.reachable((anchor.0 as i32, anchor.1 as i32), (x, y)) {
                        return Some((x as u16, y as u16));
                    }
                }
            }
        }
        None
    }

    /// 4-directional BFS reachability check; cap node visits so a giant
    /// island doesn't make this dominate the AI tick. Returns true when
    /// `goal` is connected to `start` via walkable tiles. If `start`
    /// itself isn't walkable (e.g. it's a warehouse anchor whose footprint
    /// is non-walkable), falls back to the nearest walkable 4-neighbour.
    pub fn reachable(&self, start: (i32, i32), goal: (i32, i32)) -> bool {
        if start == goal {
            return true;
        }
        let start = if self.is_walkable(start.0, start.1) {
            start
        } else {
            let mut alt = None;
            for (dx, dy) in [(1, 0), (-1, 0), (0, 1), (0, -1)] {
                let n = (start.0 + dx, start.1 + dy);
                if self.is_walkable(n.0, n.1) {
                    alt = Some(n);
                    break;
                }
            }
            match alt {
                Some(p) => p,
                None => return false,
            }
        };
        if !self.is_walkable(goal.0, goal.1) {
            return false;
        }
        const NODE_BUDGET: usize = 4_096;
        let mut visited = std::collections::HashSet::new();
        let mut queue = std::collections::VecDeque::new();
        visited.insert(start);
        queue.push_back(start);
        while let Some((x, y)) = queue.pop_front() {
            if visited.len() > NODE_BUDGET {
                return false;
            }
            for (dx, dy) in [(1i32, 0i32), (-1, 0), (0, 1), (0, -1)] {
                let n = (x + dx, y + dy);
                if !self.is_walkable(n.0, n.1) {
                    continue;
                }
                if !visited.insert(n) {
                    continue;
                }
                if n == goal {
                    return true;
                }
                queue.push_back(n);
            }
        }
        false
    }

    /// Create an empty map (all walkable) for testing or when no tile data is available.
    pub fn new_open(island_id: u8, width: u16, height: u16) -> Self {
        let size = width as usize * height as usize;
        Self {
            island_id,
            source_world_origin: (0, 0),
            width,
            height,
            walkable: vec![true; size],
            road: vec![false; size],
            city_cart_path_template: SourcePathGrid::new(
                (0, 0),
                usize::from(width),
                usize::from(height),
            ),
            carrier_path_template: SourcePathGrid::new(
                (0, 0),
                usize::from(width),
                usize::from(height),
            ),
            civilian_path_cells: vec![
                Some(SourceCivilianPathCell {
                    kind_code: 11,
                    production_kind_code: u8::MAX,
                    kind3_center_cell: false,
                    owner: 0,
                    source_ware_slot: 0,
                    plantation_path_class: 32,
                    path_class: 32,
                });
                size
            ],
            source_map_kind_cells: vec![
                Some(SourceMapKindCell {
                    kind_code: 11,
                    kind3_center_cell: false,
                    map_owner: 0,
                    ware_slot: 0,
                    map_direction: 0,
                });
                size
            ],
            city_cart_movement_speeds: vec![100; size],
            carrier_movement_speeds: vec![100; size],
            cavalry_movement_speeds: vec![100; size],
            civilian_movement_speeds: vec![100; size],
            source_terrain_heights: vec![0.0; size],
            source_land_target_sizes: vec![Some((2, 2)); size],
            source_kind4_line_of_fire_template: SourcePathGrid::new(
                (0, 0),
                usize::from(width) * 2,
                usize::from(height) * 2,
            ),
            fertilities: [7; 8],
            source_runtime_classification: 0,
            source_resource_state: IslandSourceResourceState::default(),
        }
    }

    /// Mark a tile as a road (test helper / explicit road overlay).
    pub fn set_road(&mut self, x: u16, y: u16, val: bool) {
        if x < self.width && y < self.height {
            self.road[y as usize * self.width as usize + x as usize] = val;
        }
    }
}

fn is_walkable_kind(kind: &str) -> bool {
    WALKABLE_KINDS.iter().any(|&k| kind == k)
}

fn source_controller_city_candidate_kind(kind_code: u8) -> bool {
    matches!(kind_code, 23 | 26 | 27 | 29 | 30)
}

#[cfg(test)]
mod tests {
    use super::*;
    use anno_formats::szs::IslandTile;

    #[test]
    fn from_island_resolves_tile_id_as_cod_source_id() {
        let island = Island {
            number: 3,
            width: 2,
            height: 1,
            x_pos: 0,
            y_pos: 0,
            fertilities: [7; 8],
            tiles: vec![
                IslandTile {
                    building_id: 77,
                    x: 0,
                    y: 0,
                    orientation: 0,
                    anim_count: 0,
                    flags: 0,
                },
                IslandTile {
                    building_id: 88,
                    x: 1,
                    y: 0,
                    orientation: 0,
                    anim_count: 0,
                    flags: 0,
                },
            ],
            city: None,
        };
        let road = CodBuilding {
            source_id: 20_077,
            kind: "STRASSE".to_owned(),
            ..Default::default()
        };
        let blocker = CodBuilding {
            source_id: 20_088,
            kind: "HANDWERK".to_owned(),
            ..Default::default()
        };

        let map = IslandMap::from_island(&island, &[road, blocker]);

        assert!(map.is_walkable(0, 0));
        assert!(map.is_road(0, 0));
        assert!(!map.is_walkable(1, 0));
    }

    #[test]
    fn source_world_coordinates_use_the_doubled_insel5_origin() {
        let island = Island {
            number: 10,
            width: 64,
            height: 64,
            x_pos: 110,
            y_pos: 130,
            fertilities: [7; 8],
            tiles: vec![],
            city: None,
        };
        let map = IslandMap::from_island(&island, &[]);

        assert_eq!(map.source_world_origin, (220, 260));
        assert_eq!(map.local_to_source_world((24, 21)), Some((268, 302)));
        assert_eq!(map.source_world_to_local((274, 312)), Some((27, 26)));
        assert_eq!(map.source_world_to_local((269, 303)), Some((24, 21)));
        assert_eq!(map.source_world_to_local((348, 260)), None);
        assert!(map.source_contains_world_with_margin((215, 255)));
        assert!(!map.source_contains_world_with_margin((214, 255)));
        assert!(map.source_contains_world_with_margin((352, 311)));
        assert!(!map.source_contains_world_with_margin((353, 311)));
    }

    #[test]
    fn source_runtime_classification_uses_insel5_width() {
        let mut island = Island {
            number: 0,
            width: 0x4c,
            height: 1,
            x_pos: 0,
            y_pos: 0,
            fertilities: [7; 8],
            tiles: Vec::new(),
            city: None,
        };

        assert_eq!(
            IslandMap::from_island(&island, &[]).source_runtime_classification(),
            4
        );
        island.number = 0x71;
        island.width = 0x20;
        assert_eq!(
            IslandMap::from_island(&island, &[]).source_runtime_classification(),
            0
        );
    }

    #[test]
    fn source_land_idle_anchors_resolve_static_and_packed_forms() {
        let mut static_map = IslandMap::new_open(10, 64, 64);
        static_map.source_world_origin = (220, 260);
        assert_eq!(
            static_map
                .source_land_idle_anchor(SourceTargetDescriptor::from_bytes([0x33, 10, 24, 21,])),
            Some((268, 302))
        );
        assert_eq!(
            static_map
                .source_land_idle_anchor(SourceTargetDescriptor::from_bytes([0x34, 10, 24, 21,])),
            Some((268, 302))
        );

        let mut packed_map = IslandMap::new_open(3, 30, 30);
        packed_map.source_world_origin = (530, 230);
        assert_eq!(
            packed_map.source_land_idle_anchor(SourceTargetDescriptor::from_bytes([
                0x38, 0x12, 0x34, 0x00,
            ])),
            Some((564, 256))
        );
        assert_eq!(
            packed_map.source_land_idle_anchor(
                SourceTargetDescriptor::from_source_land_route_coordinate(564, 256).unwrap(),
            ),
            Some((564, 256))
        );
    }

    #[test]
    fn kind12_anchor_uses_the_oriented_footprint_center() {
        let mut map = IslandMap::new_open(3, 8, 8);
        let root = (2, 3);
        let index = map.local_index(root).unwrap();
        map.source_land_target_sizes[index] = Some((6, 4));
        assert_eq!(map.source_kind12_anchor_center(root), Some((3, 3)));
    }

    #[test]
    fn source_land_target_rect_matches_fun_00444fe0_static_and_packed_forms() {
        let island = Island {
            number: 10,
            width: 8,
            height: 6,
            x_pos: 110,
            y_pos: 130,
            fertilities: [7; 8],
            tiles: vec![IslandTile {
                building_id: 77,
                x: 1,
                y: 2,
                orientation: 1,
                anim_count: 0,
                flags: 0,
            }],
            city: None,
        };
        let building = CodBuilding {
            source_id: 20_077,
            kind: "HANDWERK".to_owned(),
            size: (2, 4),
            ..Default::default()
        };
        let map = IslandMap::from_island(&island, &[building]);

        assert_eq!(
            map.source_land_target_rect(SourceTargetDescriptor::from_source_kind34_island_cell(
                10, 1, 2
            )),
            SourcePathTargetRect::new((222, 264), 8, 4)
        );
        assert_eq!(
            map.source_land_target_rect(SourceTargetDescriptor::from_bytes([
                0x38, 0x22, 0xec, 0x4c,
            ])),
            SourcePathTargetRect::new((0x2ec, 0x24c), 1, 1)
        );
    }

    #[test]
    fn source_land_path_grid_expands_fixed_terrain_and_blocks_kontor_cells() {
        let island = Island {
            number: 3,
            width: 3,
            height: 1,
            x_pos: 10,
            y_pos: 20,
            fertilities: [7; 8],
            tiles: vec![
                IslandTile {
                    building_id: 1,
                    x: 0,
                    y: 0,
                    orientation: 0,
                    anim_count: 0,
                    flags: 0,
                },
                IslandTile {
                    building_id: 2,
                    x: 1,
                    y: 0,
                    orientation: 0,
                    anim_count: 0,
                    flags: 0,
                },
                IslandTile {
                    building_id: 1,
                    x: 2,
                    y: 0,
                    orientation: 0,
                    anim_count: 0,
                    flags: 0,
                },
            ],
            city: None,
        };
        let mut ground = CodBuilding {
            source_id: 20_001,
            kind: "BODEN".into(),
            ..Default::default()
        };
        ground
            .properties
            .insert("Wegspeed".into(), "100,100,100,100".into());
        let mut kontor = CodBuilding {
            source_id: 20_002,
            kind: "KONTOR".into(),
            ..Default::default()
        };
        kontor
            .properties
            .insert("Wegspeed".into(), "100,100,100,100".into());
        let map = IslandMap::from_island(&island, &[ground, kontor]);
        let grid = map.source_land_path_grid(0).unwrap();

        assert_eq!(grid.is_direction_clear((20, 40)), Some(true));
        assert_eq!(grid.is_direction_clear((21, 41)), Some(true));
        assert_eq!(grid.is_direction_clear((22, 40)), Some(false));
        assert_eq!(grid.is_direction_clear((23, 41)), Some(false));
        assert_eq!(grid.metadata((20, 40)), Some(32));
    }

    #[test]
    fn source_kind4_line_of_fire_replays_the_noshot_two_by_two_overlay() {
        let island = Island {
            number: 7,
            width: 4,
            height: 1,
            x_pos: 10,
            y_pos: 20,
            fertilities: [7; 8],
            tiles: vec![IslandTile {
                building_id: 1,
                x: 1,
                y: 0,
                orientation: 0,
                anim_count: 0,
                flags: 0,
            }],
            city: None,
        };
        let no_shot = CodBuilding {
            source_id: 0x4e21,
            kind: "WALD".to_string(),
            no_shot: true,
            ..Default::default()
        };
        let map = IslandMap::from_island(&island, &[no_shot]);

        // The local cell at (1, 0) occupies raw positions (22..=23, 40..=41).
        // `FUN_0046e8b0` accepts a marker at the target endpoint but rejects
        // the same marker once it is an intermediate ray cell.
        assert!(map.source_kind4_line_of_fire_clear((20, 40), (22, 40)));
        assert!(!map.source_kind4_line_of_fire_clear((20, 40), (24, 40)));
    }

    #[test]
    fn native_idle_targets_accept_only_source_ground_or_roads() {
        let island = Island {
            number: 3,
            width: 2,
            height: 1,
            x_pos: 0,
            y_pos: 0,
            fertilities: [7; 8],
            tiles: vec![
                IslandTile {
                    building_id: 77,
                    x: 0,
                    y: 0,
                    orientation: 0,
                    anim_count: 0,
                    flags: 0,
                },
                IslandTile {
                    building_id: 88,
                    x: 1,
                    y: 0,
                    orientation: 0,
                    anim_count: 0,
                    flags: 0,
                },
            ],
            city: None,
        };
        let road = CodBuilding {
            source_id: 20_077,
            kind: "STRASSE".to_owned(),
            properties: std::collections::HashMap::from([(
                "Wegspeed".to_owned(),
                "100,100,100,100".to_owned(),
            )]),
            ..Default::default()
        };
        let building = CodBuilding {
            source_id: 20_088,
            kind: "HANDWERK".to_owned(),
            properties: std::collections::HashMap::from([(
                "Wegspeed".to_owned(),
                "100,100,100,100".to_owned(),
            )]),
            ..Default::default()
        };
        let map = IslandMap::from_island(&island, &[road, building]);

        assert!(map.source_native_idle_target_allowed((0, 0)));
        assert!(map.source_native_idle_target_allowed((1, 0)));
        assert!(IslandMap::new_open(3, 1, 1).source_native_idle_target_allowed((0, 0)));
    }

    #[test]
    fn kind13_transfer_grid_replays_radius_fixed_kinds_and_owner_overlay() {
        let island = Island {
            number: 3,
            width: 6,
            height: 1,
            x_pos: 0,
            y_pos: 0,
            fertilities: [7; 8],
            tiles: vec![
                IslandTile {
                    building_id: 4,
                    x: 0,
                    y: 0,
                    orientation: 0,
                    anim_count: 0x80,
                    flags: 0,
                },
                IslandTile {
                    building_id: 1,
                    x: 1,
                    y: 0,
                    orientation: 0,
                    anim_count: 0x80,
                    flags: 0,
                },
                IslandTile {
                    building_id: 1,
                    x: 2,
                    y: 0,
                    orientation: 0,
                    anim_count: 0x80,
                    flags: 0,
                },
                IslandTile {
                    building_id: 1,
                    x: 3,
                    y: 0,
                    orientation: 0,
                    anim_count: 0x40,
                    flags: 0,
                },
                IslandTile {
                    building_id: 2,
                    x: 4,
                    y: 0,
                    orientation: 0,
                    anim_count: 0x40,
                    flags: 0,
                },
                IslandTile {
                    building_id: 3,
                    x: 5,
                    y: 0,
                    orientation: 0,
                    anim_count: 0x80,
                    flags: 0,
                },
            ],
            city: None,
        };
        let path_properties = || {
            std::collections::HashMap::from([("Wegspeed".to_owned(), "100,100,100,100".to_owned())])
        };
        let residence_properties = || {
            std::collections::HashMap::from([
                ("Wegspeed".to_owned(), "100,100,100,100".to_owned()),
                ("ProdKind".to_owned(), "WOHNUNG".to_owned()),
            ])
        };
        let residences = CodBuilding {
            source_id: 20_001,
            kind: "PLATZ".to_owned(),
            size: (1, 1),
            properties: residence_properties(),
            ..Default::default()
        };
        let ground = CodBuilding {
            source_id: 20_002,
            kind: "BODEN".to_owned(),
            size: (1, 1),
            properties: path_properties(),
            ..Default::default()
        };
        let blocked = CodBuilding {
            source_id: 20_003,
            kind: "GEBAEUDE".to_owned(),
            size: (1, 1),
            properties: path_properties(),
            ..Default::default()
        };
        let same_owner_plaza = CodBuilding {
            source_id: 20_004,
            kind: "PLATZ".to_owned(),
            size: (1, 1),
            properties: path_properties(),
            ..Default::default()
        };
        let map = IslandMap::from_island(&island, &[residences, ground, blocked, same_owner_plaza]);
        let grid = map.source_kind13_transfer_path_grid((1, 0)).unwrap();

        assert_eq!(grid.metadata((-39, 0)), Some(0));
        assert_eq!(grid.metadata((41, 0)), Some(0));
        assert_eq!(grid.metadata((-40, 0)), None);
        assert_eq!(grid.metadata((42, 0)), None);
        assert_eq!(grid.metadata((0, 0)), Some(0x20));
        assert_eq!(grid.metadata((2, 0)), Some(0xa0));
        assert_eq!(grid.metadata((3, 0)), Some(0x20));
        assert_eq!(grid.metadata((4, 0)), Some(0x20));
        assert_eq!(grid.metadata((5, 0)), Some(0));
        assert_eq!(
            map.source_kind13_transfer_neighbor_cells((1, 0)),
            Some(vec![(2, 0)])
        );
    }

    #[test]
    fn kind13_replacement_orientation_replays_source_edge_priority() {
        let mut map = IslandMap::new_open(1, 6, 6);
        let cell = |kind_code, kind3_center_cell| {
            Some(SourceMapKindCell {
                kind_code,
                kind3_center_cell,
                map_owner: 0,
                ware_slot: 0,
                map_direction: 0,
            })
        };
        let index = |x, y| y * 6 + x;

        map.source_map_kind_cells[index(2, 1)] = cell(1, false);
        map.source_map_kind_cells[index(1, 2)] = cell(18, false);
        assert_eq!(
            map.source_kind13_replacement_orientation((2, 2), 0, (2, 2)),
            2
        );

        map.source_map_kind_cells[index(2, 1)] = cell(11, false);
        map.source_map_kind_cells[index(2, 4)] = cell(18, false);
        assert_eq!(
            map.source_kind13_replacement_orientation((2, 2), 0, (2, 2)),
            0
        );

        map.source_map_kind_cells[index(2, 4)] = cell(11, false);
        assert_eq!(
            map.source_kind13_replacement_orientation((2, 2), 0, (2, 2)),
            3
        );

        map.source_map_kind_cells[index(1, 2)] = cell(11, false);
        map.source_map_kind_cells[index(4, 3)] = cell(3, true);
        assert_eq!(
            map.source_kind13_replacement_orientation((2, 2), 0, (2, 2)),
            1
        );
        map.source_map_kind_cells[index(4, 3)] = cell(3, false);
        assert_eq!(
            map.source_kind13_replacement_orientation((2, 2), 3, (2, 2)),
            3
        );
    }

    #[test]
    fn controller_city_suitability_score_uses_source_kind_penalties() {
        let mut map = IslandMap::new_open(1, 3, 1);
        map.source_map_kind_cells = vec![
            Some(SourceMapKindCell {
                kind_code: 10,
                kind3_center_cell: false,
                map_owner: 2,
                ware_slot: 0,
                map_direction: 0,
            }),
            Some(SourceMapKindCell {
                kind_code: 25,
                kind3_center_cell: false,
                map_owner: 2,
                ware_slot: 0,
                map_direction: 0,
            }),
            Some(SourceMapKindCell {
                kind_code: 11,
                kind3_center_cell: false,
                map_owner: 1,
                ware_slot: 0,
                map_direction: 0,
            }),
        ];

        assert_eq!(map.source_controller_city_suitability_score(2), -4);
        assert_eq!(map.source_controller_city_suitability_score(1), 0);
    }

    #[test]
    fn controller_city_rectangles_replay_vertical_marks_and_row_merges() {
        let mut map = IslandMap::new_open(1, 8, 8);
        for y in 0..6 {
            for x in 0..6 {
                map.source_map_kind_cells[y * 8 + x] = Some(SourceMapKindCell {
                    kind_code: 10,
                    kind3_center_cell: false,
                    map_owner: 7,
                    ware_slot: 0,
                    map_direction: 0,
                });
            }
        }

        assert_eq!(
            map.source_controller_city_rectangles(7, 5, 5),
            vec![SourceControllerCityRectangle {
                x0: 0,
                y0: 0,
                x1: 6,
                y1: 6,
                area: 36,
            }]
        );
    }

    #[test]
    fn controller_city_predicates_replay_boundary_distance_and_density_scans() {
        let mut map = IslandMap::new_open(1, 16, 3);
        let cell = |kind_code, map_owner, ware_slot, map_direction| {
            Some(SourceMapKindCell {
                kind_code,
                kind3_center_cell: false,
                map_owner,
                ware_slot,
                map_direction,
            })
        };
        let index = |x, y| y * 16 + x;

        // `FUN_00417220` skips the first eight directional cells.
        map.source_map_kind_cells[index(1, 1)] = cell(11, 7, 0, 3);
        map.source_map_kind_cells[index(9, 1)] = cell(19, 7, 0, 0);
        map.source_map_kind_cells[index(10, 1)] = cell(11, 7, 0, 0);
        assert!(!map.source_controller_city_boundary_clear(1, 1));
        for x in 10..16 {
            map.source_map_kind_cells[index(x, 1)] = cell(19, 7, 0, 0);
        }
        assert!(map.source_controller_city_boundary_clear(1, 1));

        // One kind-16 cell is admitted, but a second consecutive one stops
        // the one-based source distance at two.
        for x in 0..16 {
            map.source_map_kind_cells[index(x, 0)] = cell(11, 7, 0, 0);
        }
        map.source_map_kind_cells[index(1, 0)] = cell(16, 7, 0, 0);
        map.source_map_kind_cells[index(2, 0)] = cell(16, 7, 0, 0);
        assert_eq!(map.source_controller_city_line_distance(7, 0, 0, 0), 2);
        map.source_map_kind_cells[index(2, 0)] = cell(11, 7, 0, 0);
        assert_eq!(map.source_controller_city_line_distance(7, 0, 0, 0), 16);

        map.source_map_kind_cells[index(2, 1)] = cell(12, 7, 0, 0);
        map.source_map_kind_cells[index(3, 1)] = cell(11, 7, 0x34, 0);
        map.source_map_kind_cells[index(4, 1)] = cell(11, 7, 5, 0);
        map.source_map_kind_cells[index(5, 1)] = cell(11, 7, 5, 0);
        map.source_map_kind_cells[index(6, 1)] = cell(12, 6, 0, 0);
        assert_eq!(map.source_controller_city_green_density(7, 4, 1, 3), 2);
        assert_eq!(map.source_controller_city_ware_five_density(7, 4, 1, 3), 2);
    }

    #[test]
    fn controller_city_candidate_segments_replay_source_pass_order() {
        let mut map = IslandMap::new_open(1, 16, 16);
        let cell = |kind_code, map_owner| {
            Some(SourceMapKindCell {
                kind_code,
                kind3_center_cell: false,
                map_owner,
                ware_slot: 0,
                map_direction: 0,
            })
        };
        let index = |x, y| y * 16 + x;

        for y in 4..10 {
            map.source_map_kind_cells[index(8, y)] = cell(23, 7);
        }
        map.source_map_kind_cells[index(8, 10)] = cell(11, 7);
        for x in 4..10 {
            map.source_map_kind_cells[index(x, 12)] = cell(26, 7);
        }
        map.source_map_kind_cells[index(10, 12)] = cell(11, 7);

        let segments = map.source_controller_city_candidate_segments(7, 0, 0, 16, 16, 3, 3);
        assert!(
            segments.starts_with(&[SourceControllerCityCandidateSegment {
                x0: 8,
                y0: 4,
                x1: 8,
                y1: 10,
                length: 6,
            }])
        );
        assert!(segments.contains(&SourceControllerCityCandidateSegment {
            x0: 4,
            y0: 12,
            x1: 10,
            y1: 12,
            length: 6,
        }));
    }

    #[test]
    fn source_carrier_template_uses_speedtyp_zero() {
        let island = Island {
            number: 3,
            width: 1,
            height: 1,
            x_pos: 0,
            y_pos: 0,
            fertilities: [7; 8],
            tiles: vec![IslandTile {
                building_id: 77,
                x: 0,
                y: 0,
                orientation: 0,
                anim_count: 0,
                flags: 0,
            }],
            city: None,
        };
        let ground = CodBuilding {
            source_id: 20_077,
            kind: "BODEN".to_owned(),
            size: (1, 1),
            source_position_offset: 10,
            properties: std::collections::HashMap::from([(
                "Wegspeed".to_owned(),
                "100,125,150,175".to_owned(),
            )]),
            ..Default::default()
        };

        let map = IslandMap::from_island(&island, &[ground]);

        assert_eq!(map.carrier_path_grid().metadata((0, 0)), Some(32));
        assert_eq!(map.city_cart_path_grid().metadata((0, 0)), Some(48));
        assert_eq!(map.carrier_movement_speed((0, 0)), Some(100));
        assert_eq!(map.city_cart_movement_speed((0, 0)), Some(150));
        assert!((map.source_terrain_height((0, 0)).unwrap() - 0.28).abs() < f32::EPSILON);
    }

    #[test]
    fn plantation_worker_grid_marks_only_matching_raw_resource_cells() {
        let mut map = IslandMap::new_open(3, 3, 1);
        map.civilian_path_cells[1] = Some(SourceCivilianPathCell {
            kind_code: 9,
            production_kind_code: u8::MAX,
            kind3_center_cell: false,
            owner: 2,
            source_ware_slot: 0x2d,
            plantation_path_class: 41,
            path_class: 41,
        });
        map.civilian_path_cells[2] = Some(SourceCivilianPathCell {
            kind_code: 9,
            production_kind_code: u8::MAX,
            kind3_center_cell: false,
            owner: 2,
            source_ware_slot: 0x2e,
            plantation_path_class: 42,
            path_class: 42,
        });

        let grid = map.plantation_worker_path_grid((0, 0), (0, 0), (1, 1), 2, 2, 0x2d, &[]);

        assert_eq!(grid.metadata((0, 0)), Some(0x28));
        assert_eq!(grid.metadata((1, 0)), Some(41));
        assert!(grid.route_to((0, 0), (1, 0)).is_ok());
        assert!(grid.route_to((0, 0), (2, 0)).is_err());
    }

    #[test]
    fn plantation_worker_grid_uses_the_live_growth_resource_selector() {
        let map = IslandMap::new_open(3, 2, 1);
        let growth = SourceMapCellState {
            source_map_owner_slot: 2,
            source_output_ware_slot: 0,
            source_growth_resource_ware_slot: 0x2d,
            source_production_kind_code: 10,
            source_path_class: 46,
            kind_code: 10,
            ..SourceMapCellState::new_static(
                3,
                1,
                0,
                &CodBuilding {
                    kind: "WALD".into(),
                    properties: [("ProdKind".into(), "ROHSTWACHS".into())].into(),
                    ..Default::default()
                },
                0,
            )
            .unwrap()
        };

        let grid = map.plantation_worker_path_grid((0, 0), (0, 0), (1, 1), 2, 2, 0x2d, &[growth]);

        assert_eq!(grid.metadata((1, 0)), Some(46));
        assert!(grid.route_to((0, 0), (1, 0)).is_ok());
    }

    #[test]
    fn type17_terrain_grid_uses_fixed_costs_and_unreserved_resource_targets() {
        let map = IslandMap::new_open(3, 3, 1);
        let raw_resource = |x, reserved| SourceMapCellState {
            source_output_ware_slot: 0x34,
            source_resource_reserved: reserved,
            kind_code: 1,
            ..SourceMapCellState::new_static(
                3,
                x,
                0,
                &CodBuilding {
                    kind: "BODEN".into(),
                    properties: [("Ware".into(), "GRAS".into())].into(),
                    ..Default::default()
                },
                0,
            )
            .unwrap()
        };
        let special_terrain = SourceMapCellState {
            source_output_ware_slot: 0x35,
            kind_code: 9,
            ..SourceMapCellState::new_static(
                3,
                0,
                0,
                &CodBuilding {
                    kind: "ROHSTOFF".into(),
                    properties: [("Ware".into(), "ERDE".into())].into(),
                    ..Default::default()
                },
                0,
            )
            .unwrap()
        };

        let grid = map.source_type17_terrain_path_grid(
            (1, 0),
            0x34,
            &[
                special_terrain,
                raw_resource(1, false),
                raw_resource(2, true),
            ],
        );

        assert_eq!(grid.metadata((0, 0)), Some(0x20));
        assert_eq!(grid.metadata((1, 0)), Some(0xa0));
        assert_eq!(grid.metadata((2, 0)), Some(0x20));
    }

    #[test]
    fn from_island_blocks_the_full_rotated_source_footprint() {
        let island = Island {
            number: 3,
            width: 3,
            height: 2,
            x_pos: 0,
            y_pos: 0,
            fertilities: [7; 8],
            tiles: vec![
                IslandTile {
                    building_id: 1,
                    x: 0,
                    y: 0,
                    orientation: 0,
                    anim_count: 0,
                    flags: 0,
                },
                IslandTile {
                    building_id: 2,
                    x: 1,
                    y: 0,
                    orientation: 1,
                    anim_count: 0,
                    flags: 0,
                },
            ],
            city: None,
        };
        let ground = CodBuilding {
            source_id: 20_001,
            kind: "BODEN".to_owned(),
            size: (3, 2),
            ..Default::default()
        };
        let blocker = CodBuilding {
            source_id: 20_002,
            kind: "HANDWERK".to_owned(),
            size: (2, 1),
            ..Default::default()
        };

        let map = IslandMap::from_island(&island, &[ground, blocker]);

        assert!(map.is_walkable(0, 0));
        assert!(!map.is_walkable(1, 0));
        assert!(!map.is_walkable(1, 1));
        assert!(map.is_walkable(2, 1));
    }

    #[test]
    fn from_island_leaves_unresolved_source_id_blocked() {
        let island = Island {
            number: 3,
            width: 1,
            height: 1,
            x_pos: 0,
            y_pos: 0,
            fertilities: [7; 8],
            tiles: vec![IslandTile {
                building_id: 77,
                x: 0,
                y: 0,
                orientation: 0,
                anim_count: 0,
                flags: 0,
            }],
            city: None,
        };

        let map = IslandMap::from_island(&island, &[]);

        assert!(!map.is_walkable(0, 0));
    }

    #[test]
    fn open_map_all_walkable() {
        let map = IslandMap::new_open(0, 10, 10);
        assert!(map.is_walkable(0, 0));
        assert!(map.is_walkable(9, 9));
        assert!(!map.is_walkable(-1, 0));
        assert!(!map.is_walkable(10, 0));
    }

    #[test]
    fn set_walkable() {
        let mut map = IslandMap::new_open(0, 10, 10);
        assert!(map.is_walkable(5, 5));
        map.set_walkable(5, 5, false);
        assert!(!map.is_walkable(5, 5));
    }

    #[test]
    fn can_fit_respects_bounds_and_blocks() {
        let mut map = IslandMap::new_open(0, 10, 10);
        assert!(map.can_fit(0, 0, 3, 3));
        assert!(!map.can_fit(8, 8, 3, 3)); // would overflow
        map.set_walkable(2, 2, false);
        assert!(!map.can_fit(0, 0, 3, 3)); // blocker hits the footprint
        assert!(map.can_fit(3, 3, 3, 3)); // clear away from blocker
    }

    #[test]
    fn coastal_tiles_are_on_the_perimeter() {
        let map = IslandMap::new_open(0, 5, 5);
        // Corners and edges are coastal.
        assert!(map.is_coastal(0, 0));
        assert!(map.is_coastal(2, 0));
        assert!(map.is_coastal(4, 4));
        // Interior tile is not.
        assert!(!map.is_coastal(2, 2));
    }

    #[test]
    fn reachable_via_walkable_path() {
        let map = IslandMap::new_open(0, 10, 10);
        assert!(map.reachable((0, 0), (9, 9)));
    }

    #[test]
    fn reachable_blocked_by_wall() {
        let mut map = IslandMap::new_open(0, 10, 10);
        // Vertical wall at x=5 cuts the map in two.
        for y in 0..10u16 {
            map.set_walkable(5, y, false);
        }
        assert!(!map.reachable((0, 0), (9, 9)));
        assert!(map.reachable((0, 0), (4, 4)));
    }

    #[test]
    fn find_reachable_spot_avoids_isolated_island() {
        let mut map = IslandMap::new_open(0, 10, 10);
        // Cut off the right half so reachable spots only exist on the left.
        for y in 0..10u16 {
            map.set_walkable(5, y, false);
        }
        // Anchor at (1,1). Tile (8,8) is walkable but unreachable; the
        // reachable variant should pick a left-side spot instead.
        let spot = map.find_reachable_spot(8, 8, 1, 1, 9, (1, 1)).unwrap();
        assert!((spot.0 as i32) < 5, "got unreachable spot {:?}", spot);
    }

    #[test]
    fn find_open_spot_spirals_around_blocked_center() {
        let mut map = IslandMap::new_open(0, 10, 10);
        // Wall the 2x2 around (5,5).
        for x in 4..=6 {
            for y in 4..=6 {
                map.set_walkable(x, y, false);
            }
        }
        let pos = map.find_open_spot(5, 5, 2, 2, 5).expect("found spot");
        // Picked footprint must be walkable.
        assert!(map.can_fit(pos.0 as i32, pos.1 as i32, 2, 2));
        // And must lie outside the blocked block.
        let in_blocked = (pos.0 as i32) >= 3
            && (pos.0 as i32) <= 6
            && (pos.1 as i32) >= 3
            && (pos.1 as i32) <= 6;
        assert!(!in_blocked, "got {:?} which overlaps the 2x2 wall", pos);
    }
}
